spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 372394557118-ggh7v0u3gtcsap5fbcos175262hgmivs.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: 6G2gzqVQPRh62UqESmGk
            client-secret: D9LR8W3ehS
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response